### ISSUE TITLE
Finding the -fltoken arguments

### ISSUE THREAD

**Issue by HENRYMARTIN5** [Retransition/Forcer#2]
Hello there,
I am currently developing a battleye emulator script, but cannot seem to get the game to consistently launch with battleye. Then, I found this project, and I am now trying to find the proper arguments. I thought you might be able to help.

PS:
I tried to contact you through discord, but it didn't work. I had to resort to creating an issue

**Comment by JayOnGitHu** [comment]
Hi! Did he end up getting back to you? I'd love to give this a shot because for some reason when I am on EAC I get really bad stuttering :/

**Comment by HENRYMARTIN5** [comment]
Nope. @JayOnGitHu

**Comment by exact** [comment]
hi this was my project sorta long ago, seems like it no longer works as of 2023

**Comment by HENRYMARTIN5** [comment]
Ah well

**Comment by exact** [comment]
> Ah well

Hi update, I know this is closed now but its possible for this to work, the game now uses EAC_EOS for easyanticheat not normal EAC and BattlEye seems the same however on top of all that there seems to be a new JWT like token structure for launching/verifying you can pull anti-cheat specific ones like the fltokens before but they seem to invalidate way easier and not work until next update like last time, this project is possible in theory now but getting the new JWTs is much harder. I've tested some and managed to get both anticheats to launch but after a few days the tokens become invalid and i get kicked from game, decoding the tokens reveals a creation and maybe expiration time so its probably alot harder if not impossible to spoof tokens now, best of luck to you if you're still trying to force, for me though nowadays it almost always auto-uses EAC and i have no issues with it :)
